### ISSUE TITLE
Concurrent tasks limit

### ISSUE THREAD

**Issue by xupyprmv** [yegor256/xdsd#43]
As anyone can see in §32 http://at.teamed.io/policy.html

> When you start working with us, you’ll have two tasks maximum. When your rating is over 60, you’ll get up to five tasks.

My rating is >60 for more than 2 months, but I still have only 2 concurrent tasks. Concurrent tasks limit must be increased to 5 automatically when user have rating >60 during some fixed amount of time (1-2 weeks).

**Comment by davvd** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by CarlosGines** [comment]
@yegor256 I have this problem too (my rating is also above 60). It is even more confusing since I have:
- General concurrent task limit: 2
- Concurrent task limit on project Takes: 5
- Concurrent task limit on project Netbout: ?

And as a matter of fact I am not receiving more that 2 concurrent tasks.

<img width="760" alt="captura de pantalla 2016-03-15 a las 16 59 05" src="https://cloud.githubusercontent.com/assets/16798121/13784723/a659f9b8-ead0-11e5-94d7-7c9d8ed676f3.png">

**Comment by yegor256** [comment]
@original-brownbear I'm closing this task, since it's not relevant to this repo anymore. If you still believe that there is an issue in our [Policy](http://www.zerocracy.com/policy.html), please re-submit it to this repo: [zerocracy/datum](https://github.com/zerocracy/datum/issues)
